version: '3.8'
services:
    web_app:
        container_name: djangoApp
        build: 
            context: .
            dockerfile: dockerfile
        ports: 
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - database

    database:
        container_name: djangoDB
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: appDB
            MYSQL_USER: root
            MYSQL_PASSWORD: password1
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - .dbdata:/var/lib/mysql